# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DgwEQTE8RiuheCnjk63Nq_qH1l9N4Bd-
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Cargar dataset
df = pd.read_csv('university_student_data.csv')

#Mostrar primeras filas
df.head()

#Informacion general
df.info()

#Estadisticas
df.describe()

#Ver columnas
print(df.columns)

plt.figure(figsize=(10,5))

sns.lineplot(
    data=df,
    x='Year',
    y='Retention Rate (%)',
    hue='Term',
    marker='o'
)

plt.title('Retention Rate Trends Over Time')
plt.show()

term_comparison = df.groupby('Term')['Enrolled'].mean()

term_comparison.plot(
    kind='bar',
    figsize=(6,5)
)

plt.title('Spring vs Fall Enrollment')
plt.ylabel('Avarage Enrollment')
plt.show()

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Configuracion
st.set_page_config(
    page_title = "University Dashboard",
    layout = "wide"
)

st.title("University Student Analytics Dashboard")

#Cargar dataset
df = pd.read_csv('university_student_data.csv')

#Sidebar
st.sidebar.header("Filters")

years = st.sidebar.multiselect(
    "Select Year",
    options=sorted(df["Year"].unique()),
    default=sorted(df["Year"].unique())
)

terms = st.sidebar.multiselect(
    "Select Terms",
    options=df["Term"].unique(),
    default=df["Term"].unique()
)

#Filtrado
filtered_df = df[
    (df["Year"].isin(years)) &
    (df["Term"].isin(terms))
]

#KPIs
st.subheader("Key performance Indicators")

col1, col2, col3 = st.columns(3)

avg_retention = filtered_df["Retention Rate (%)"].mean()
avg_satisfaction = filtered_df["Student Satisfaction (%)"].mean()
total_enrolled = filtered_df["Enrolled"].sum()

col1.metric(
    "Avarage Retention",
    f"{avg_retention:.1f}%"
)

col2.metric(
    "Avarage Satisfaction",
    f"{avg_satisfaction:.1f}%"
)

col3.metric(
    "Total Enrolled",
    f"{total_enrolled}"
)

#Opciones visuales
st.subheader("Visualization Settings")

colA, colB = st.columns(2)

with colA:
  show_grid = st.checkbox("Show Grid", value=True)

with colB:
  line_color = st.color_picker(
      "Choose Line Color",
      "#1f77b4"
  )

#Grafico
st.subheader("Retention Rate Trends")

fig1, ax1 = plt.subplots(figsize=(10,5))

sns.lineplot(
    data=filtered_df,
    x="Year",
    y="Retention Rate (%)",
    hue="Term",
    marker="o",
    ax=ax1
)

ax1.grid(show_grid)
ax1.set_title("Retention Rate Over Time")

st.pyplot(fig1)

#Grafico 2
st.subheader("Student Satisfaction")

fig2, ax2 = plt.subplots(figsize=(10,5))

sns.barplot(
    data=filtered_df,
    x="Year",
    y="Student Satisfaction (%)",
    hue="Term",
    ax=ax2
)

ax2.grid(show_grid)

st.pyplot(fig2)

#Grafico 3

st.subheader("Depertment Enrollment")

dept_data = filtered_df[[
    "Engineering Enrolled",
    "Businness Enrolled",
    "Arts Enrolled",
    "Scince Enrolled"
]].sum()

fig3, ax3 = plt.subplots(figsize=(7,7))

ax3.pie(
    dept_data,
    labels=dept_data.index,
    autopct='%1.1f%%'
)

st.pyplot(fig3)

#Tabs

tab1, tab2 = st.tabs([
    "Filtered Data",
    "Complete Dataset"
])

with tab1:
  st.dataframe(
      filtered_df.reset_index(drop=True),
      use_container_width=True
  )

with tab2:
  st.dataframe(
      df,
      use_container_width=True
  )

#Footer
st.caption(
    "Interactive dashboard created with Streamlit for university data analysis."
)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# matplotlib
# seaborn

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # University Student Analytics Dashboard
# 
# Este proyecto analiza datos de admision, matricula, satisfaccion estudiantil utilizando python y Streamlit.
# 
# ## Objetivo del proyecto
# El objetivo de este dashboard es visualizar y resumir de forma interactiva la informacion estudiantil de la universidad para apoyar la toma de decisiones basada en datos.
# 
# ## Caracteristicas
# 
# - Filtros interactivos por año y periodo academico
# - Analisis de tasas de retencion
# - Analisis de satisfaccion estudiantil
# - Visualizacion de metriculas por departamento
# - Indicadores KPI
# - Graficos y tablas dinamicas
# 
# # Tecnologias usadas
# 
# - Python
# - Pandas
# - Matplotlib
# - Seaborn
# - Streamlit
# 
# ## Archivos incluidos
# 
# - 'app.py' => Dashboard principal en Streamlit
# - 'requirements.txt' => librerias necesarias
# - 'README.md' => Documentacion del proyecto
# - 'university_student_data.csv' => Dataset utilizado en el analisis
#